"use client";

import { Inter } from "@next/font/google";
import "./globals.css";

import { ThemeProvider, CssBaseline } from "@mui/material";
import { AppHeader } from "./AppHeader";
import { useTheme } from "../lib/useTheme";
import { Theme } from "@emotion/react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { theme } = useTheme();
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
        <body id="__next">
          <CssBaseline />
          <AppHeader />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
